import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import HireUs from "@/components/HireUs";
import AnimatedText from "@/components/AnimatedText";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import Link from "next/link";
import { LinkArrow } from "@/components/icons";

export default function Home() {
  return (
    <>
      <Head>
        <title>Paradigm Labs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="Paradigm Labs"
                className="w-full h-auto"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="We drive experiences for products  with  purpose."
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium">
              We’re Africas change-makers, in a complex world. The prodcts we support are positioned to be purposeful and powerful while also fluid and free-forming.We’re embracers of change. When we drive the change, a product can connect with its audience, captivate the hearts and minds of customers, and convert cross-channel.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="mailto:steve@designlabafrica.com"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold border border-solid border-dark hover:bg-light hover:text-dark"
                >
                  Contact Us
                  <LinkArrow className={"w-5 ml-1"} />
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireUs></HireUs>
      </main>
    </>
  );
}
